In [1]:
mylist1 = [1,2,3,4,5]
mylist2=[2,3,4,5,6]

In [2]:
mylist1/mylist2

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [3]:
sales=[2345, 3775,5676,3345]
profit=[325,445,445,333]

In [4]:
profit/sales

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [5]:
import numpy as np

In [6]:
sales_array=np.array(sales)

In [7]:
sales_array

array([2345, 3775, 5676, 3345])

In [8]:
profit_array=np.array(profit)

In [9]:
profit_array

array([325, 445, 445, 333])

In [10]:
profit_array/sales_array

array([0.13859275, 0.11788079, 0.07840028, 0.09955157])

In [11]:
sales*2

[2345, 3775, 5676, 3345, 2345, 3775, 5676, 3345]

In [12]:
sales_array*2

array([ 4690,  7550, 11352,  6690])

In [13]:
sales[0]=0

In [14]:
sales

[0, 3775, 5676, 3345]

In [15]:
sales_array[0]=0

In [16]:
sales_array

array([   0, 3775, 5676, 3345])

In [17]:
sales_1=sales[0:2]

In [18]:
sales_1

[0, 3775]

In [19]:
sales_1[0]=1000

In [20]:
sales_1

[1000, 3775]

In [21]:
sales

[0, 3775, 5676, 3345]

In [22]:
sales_array_1=sales_array[0:2]

In [23]:
sales_array_1

array([   0, 3775])

In [24]:
sales_array_1[0]=1000

In [25]:
sales_array_1

array([1000, 3775])

In [26]:
sales_array

array([1000, 3775, 5676, 3345])

In [27]:
sales_array_2=sales_array.copy()

In [28]:
sales_array_2

array([1000, 3775, 5676, 3345])

In [29]:
sales_array_2[0]=0

In [30]:
sales_array_2

array([   0, 3775, 5676, 3345])

In [31]:
sales_array

array([1000, 3775, 5676, 3345])

In [32]:
list1=[1,2,3,4,5,'R']

In [33]:
list1

[1, 2, 3, 4, 5, 'R']

In [34]:
array_1=np.array(list1)

In [35]:
array_1

array(['1', '2', '3', '4', '5', 'R'], dtype='<U21')

In [36]:
tuple_1=(1,2,3,4,'R')

In [37]:
tuple_1

(1, 2, 3, 4, 'R')

In [38]:
array_1

array(['1', '2', '3', '4', '5', 'R'], dtype='<U21')